global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'edgex'
    static_configs:
      - targets: ['edgex-exporter:9410']
        labels:
          group: 'edgex'
